{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zigbee2mqtt.fullname" . }}
  labels:
{{ include "zigbee2mqtt.labels" . | indent 4 }}
{{- if .Values.ui.service.labels }}
{{ toYaml .Values.ui.service.labels | indent 4 }}
{{- end }}
{{- with .Values.ui.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.ui.service.type "ClusterIP") (empty .Values.ui.service.type)) }}
  type: ClusterIP
  {{- if .Values.ui.service.clusterIP }}
  clusterIP: {{ .Values.ui.service.clusterIP }}
  {{end}}
{{- else if eq .Values.ui.service.type "LoadBalancer" }}
  type: {{ .Values.ui.service.type }}
  {{- if .Values.ui.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.ui.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.ui.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.ui.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.ui.service.type }}
{{- end }}
{{- if .Values.ui.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.ui.service.externalIPs | indent 4 }}
{{- end }}
  {{- if .Values.ui.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.ui.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      protocol: TCP
      targetPort: http
{{ if (and (eq .Values.ui.service.type "NodePort") (not (empty .Values.ui.service.nodePort))) }}
      nodePort: {{.Values.ui.service.nodePort}}
{{ end }}
  selector:
    app.kubernetes.io/name: {{ include "zigbee2mqtt.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}